### PR TITLE
Merge pull request #1 from emhoracek/master

### PR DESCRIPTION
**Pull request by vagita24**
fix cell to cel and cells to cels

### CODE REVIEW

**Comment by emhoracek** [comment]
Thanks for the PR -- you can see in the "Files changed" tab that your changes are missing, though. I'll work with you to get this fixed later tonight.

**Comment by vagita24** [comment]
@emhoracek what to do now..

**Comment by emhoracek** [comment]
@vagita24 I looked on your fork and I don't see any changes, so I think you must have missed committing them?

If you have the changes ready, try running `git add <filename>` for each changed file to "stage" them to get ready to commit. Then run `git commit` to commit the changes. Then run `git push` to push the changes. When you make your pull request, you should see the changes you made listed in the pull request.

If you run into any problems with any of these steps, comment here or on the issue with some details about what questions you have.

There's a free video series here if like to learn from videos: http://makeapullrequest.com/

**Comment by vagita24** [comment]
@emhoracek I have propsed the changes on my master branch in my local repo. Now, I have to make another pull request or do something else?

**Comment by emhoracek** [comment]
@vagita24 yes, please make another pull request. Thanks!

**Pull request closed without merging**
