### PR TITLE
[WIP]Add demo doll

### LINKED ISSUE #26: Add a demo doll to the index page
The index page for the site is a bit bare right now: 

screen shot 2017-09-30 at 7 38 13 pm

Let's add a "demo doll" to the index page, then encourage folks to create an account to play with other sets. See this beautiful mockup:

smooch

Please be creative in your interpretation of this mockup. ^_^

The index page can be found at `/haskell/templates/index.tpl`.

To get the code for a demo doll, you can copy code from demos in the `docs` folder. The demos are at `/docs/example-sets/`. I would recommend "yura" because it's a small and simple doll. Copy the folder to `/haskell/static/`, then copy the HTML from that folder into the `index.tpl` template.

It would be even better if you could find an artist that gives explicit permission for their work to be used in this way. I haven't been able to get a hold of any artists so far. -_-

### PR DESCRIPTION
**Pull request by aklap**
WIP Fixes #26.

First pass on updating the home page with a demo doll.

### CODE REVIEW

**Comment by emhoracek** [comment]
@aklap sorry for leaving this for 7 whole months :sob: I finally pulled and was able to build and it looks GREAT! Thanks so much for putting all this work in.

Is this ready for review and merge?

BTW I had to do some tweaks to get the app to compile on the latest MacOSX -- if you run into that problem, try changing the `resolver` line in the `stack.yaml` to `resolver: lts-9.21`.

**Comment by aklap** [comment]
Hey @emhoracek I completely forgot I even made this PR. Thank you for taking a look at it and giving such positive feedback! This was such a great learning experience for me and intro to Haskell.

I'm not sure;  since it's been a while I should probably take a look at what I did here first before we review and merge anything. I feel like I've learned so much about the frontend as well in the past 6-7 months, that I should just review what I did with that added knowledge 🙂 

Thanks for the info re: MacOS, I'm going to try to take a look at this tonight or tomorrow latest!

**Comment by aklap** [comment]
@emhoracek Thanks for the tip about changing the `resolver`.  I'm getting this error message when I try to build: 

```
Didn't see hspec-fn-0.1.1.0 in your package indices.
Updating and trying again.
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/                     
Downloading timestamp                                                                
No updates to your package index were found                                          
Update complete                                                                      
The following package identifiers were not found in your indices: hspec-fn-0.1.1.0
Perhaps you meant hspec2, hspec, hspec-snap, or hspec-wai?
```

**Comment by emhoracek** [comment]
Another long delay but I just pushed a fix to the stack.yaml, so you may be able to build now. Let me know if you run into any other problems -- I had some brew dependencies get out of whack.

**Comment by huggablemonad** [comment]
I had to change `cells` to `cels` in `app/static/yura/setdata.js` (see #78), otherwise the doll doesn't show up.

missing-demo-doll

Other than that, it looks really good! :+1:

**Pull request merged**
