### PR TITLE
Turn runProgram into runCommand so it can have output

### PR DESCRIPTION
**Pull request by emhoracek**
When runCommand can return output, we can use it for all the shell commands!

### CODE REVIEW

**Comment by emhoracek** [comment]
@ear appreciate your thoughts on this!

**Comment by ear** [comment]
Hi @emhoracek! I pulled your branch, read through System.Process, and then coded some changes. This way you can see what I mean by reading a few lines of code instead of pages of text 🤐 

I am not quite sure what is the process to attach more code to a pull request I don't own on github 😶 so I pulled it into my fork, added one commit, and pushed it. You can find it [here](https://github.com/ear/smooch/commit/a969744aa30330d27a6eed9aedb1ef16f094fb03).

In brief it modifies runCommand like this:

```haskell
runCommand :: WantOutput -> String -> String -> EitherT Text IO Text
```

And defines (passing) tests for it:

adsasdasdasdasdasd

Let me know what you think! I am also wondering whether that type should end in `… String`. There's an awful lot of `T.unpack`-ing in almost all of the runCommand call sites. Maybe it could be a simplification.

🖖

**Comment by ear** [comment]
I just had a realization.

The error checking is different between `runCommand WantOutput` and `runCommand NoOutput`. The “tag”-type I added as first argument was eating at me though. It is both elegant because it expresses the intent clearly and a somewhat ham-fisted attempt for clarity.

What just popped up in my mind is that one could simply have two different functions! I wanted to mention that. It's such a stupid thing I can't believe I didn't think of it at the time.

What would one call them… I'm starting to believe the “tag” `WantOutput | NoOutput` is actually better-looking than all the possible names I'm coming up with right now 😆

**Comment by emhoracek** [comment]
@ear just want you to know that I appreciate the thought you're putting into this! I'm pretty busy this week with work and my parents visiting but I'll respond as soon as I have some time. Thanks!

**Comment by ear** [comment]
@emhoracek thanks for the quick answer! It's mostly that I am slowly rediscovering why I loved writing haskell ~10 years ago… and asking myself… why did I stop??? :man_facepalming: :man_shrugging: It's been fun to have this code in the back of my mind and learning how things changed while I wasn't looking.

Got me back to reading Haskell papers too. That's loads of fun. I've been perusing my old old old favorite http://okmij.org/ftp/ this week. Glad that Oleg guy is still around and publishing stuff.

**Comment by emhoracek** [comment]
@ear Sorry I kinda disappeared on this project, and it's been hard to pick up again because I lost the context. I'm going to go ahead and merge this PR. Since your idea seems to be an evolution of that one, maybe you could turn our fork into your own PR? Then I could assess it on its own merits instead of trying to remember how it fits into this PR.

**Pull request merged**
