### PR TITLE
EitherT refactor

### PR DESCRIPTION
**Pull request by ear**
I coded up the changes! :man_technologist: ☕️ 

In the process I discovered that the package `either` depends on the package `bifunctors` which implements handy functions like [`first`](http://hackage.haskell.org/package/bifunctors-3.0/docs/src/Data-Bifunctor.html).

I thought I'd use that instead of [`mapLeft`](http://hackage.haskell.org/package/either-4.4.1.1/docs/src/Data.Either.Combinators.html#mapLeft) I had found before in [`Data.Either.Combinators`](http://hackage.haskell.org/package/either-4.4.1.1/docs/Data-Either-Combinators.html) (also from `either` but whose documentation says, quote: _Most of these combinators are provided for pedagogical purposes and exist in more general forms in other libraries._ Go figure!)

Let me know what you think! 🌠

### CODE REVIEW

**Comment by emhoracek** [comment]
@ear Thanks for the PR! This looks great. It would be cool if I could review this on the stream tomorrow, so viewers can learn a little about EitherT and my preferred code style on this project. Would you be okay with that? I'm also happy to review it off the stream if that's more comfortable for you.

**Comment by ear** [comment]
That'd be nice! I have something more I'd like to propose but I didn't want to complicate this one. Let me see if I can write a short summary now…

**Comment by ear** [comment]
It struck me as strange to see uses of IO actions like `createProcess` and `hGetContents` in [Shell.hs](https://github.com/emhoracek/smooch/blob/master/haskell/src/Shell.hs#L18-L24) that:
- are in `EitherT Text IO a`
- do *not* use `tryIO`

I noticed that when I tried to change likes like 27 and 28 from using explicit `return $ Right $ …` to `right` and `return $ Left $ …` to `left`. That is not possible because it's an `IO` computation that can throw exceptions which is then wrapped in the `EitherT` on line 17 explicitly.

Given the strict nature of `tryIO` I am given to think that we should be put those as close as possible the call site of actions that can throw. I wonder if I am anywhere close to right on this 😄 

If we do, the code would look like this:

```haskell
-- Gets the transparency color from a kcf palette.
transColor :: PaletteFilename -> EitherT T.Text IO String
transColor paletteLoc = do
  (_,colorOut, err, ph)  <- tryIO $ createProcess (shell $ "cel2pnm -t " <> paletteLoc) { std_out = CreatePipe, std_err = CreatePipe }
  result <- tryIO $ waitForProcess ph
  errMsg <- case err of
              Just x  -> tryIO $ hGetContents x
              Nothing -> return "no error message"
  color <- case colorOut of
              Just x -> tryIO $ hGetContents x
              Nothing -> return "no color"
  case result of
    ExitSuccess -> right color
    ExitFailure n -> left $ T.pack ("Error while finding transparency color. Exit code: " <> show n <> ". Error: " <> errMsg)
```

I guess we can go further with:

```haskell
  errMsg <- maybe (return "no error message") (tryIO . hGetContents) err
  color <- maybe (return "no color") (tryIO . hGetContents) colorOut
```

But I wonder if the simpler way to handle this is actually something like:

```haskell
maybeToEither :: a -> Maybe b -> Either a b
maybeToEither = (`maybe` Right) . Left
```

`fmap`-ped to lift the `Maybe`s into the EitherT _horror_-handling monad 😆 

If I am seeing this correctly, this way, just like `tryIO` lifts the handling of thrown `IOException` into `Left`s of `EitherT`, we can lift the `Nothing`s in the same place. Then do-nation will handle the failures for us transparently.

The reason I didn't try any of this though is purely because then `tryIO` needs to be shared between Upload.hs, Shell.hs as well as the test files! While trying it out I actually _moved_ tryIO from Upload.hs to Shell.hs and then moved the test from UploadSpec.hs to ShellSpec.hs.

I hope this made sense, I took way less time to write this comment than any of the previous ones! 😪

**Comment by ear** [comment]
OK I can't seem to get away from trying to figure out this `EitherT` craziness on this Saturday! 🤓 

The hardest error condition to find properly was the second test case below where there is no output.

Here is what I came up with:

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Data.Text
import qualified Data.Text as T

import Data.Monoid ((<>))
import Data.Bifunctor (first)

import System.IO
import System.Exit (ExitCode (..))
import System.Process

import Control.Exception

import Control.Monad (when)
import Control.Monad.Trans
import Control.Monad.Trans.Either

tryIO m = EitherT $ first showIOException <$> try m
  where showIOException = pack . show :: IOException -> Text

maybeToEitherT :: (Monad m) => e -> Maybe a -> EitherT e m a
maybeToEitherT = (`maybe` right) . left

main = do
  x <- runEitherT $ action "printf \\#a29cd5" -- simulate getting a color back
  print x
  x <- runEitherT $ action "true" -- command executed successfully but no output
  print x
  x <- runEitherT $ action "false" -- command executed unsuccessfully
  print x
  x <- runEitherT $ action "poop" -- no such command
  print x

action :: String -> EitherT Text IO Text
action command = do
  (_, maybeOut, maybeErr, ph) <- tryIO $ createProcess (shell command) {
      std_out = CreatePipe
    , std_err = CreatePipe
  }
  res <- tryIO $ waitForProcess ph
  err <- maybeToEitherT "no error message" maybeErr
  errMsg <- hGetText err
  out <- maybeToEitherT "no output" maybeOut
  outMsg <- hGetText out
  case res of
    ExitSuccess | T.length outMsg == 0 -> left "no color"
                | otherwise            -> right outMsg
    ExitFailure n -> left errMsg'
      where
        errMsg' = "(" <> pack (show n) <> ") error finding bg color: " <> errMsg

hGetText :: Handle -> EitherT Text IO Text
hGetText h = tryIO $ pack <$> hGetContents h
```

```haskell
*Main> main
Right "#a29cd5"
Left "no color"
Left "(1) error finding bg color: "
Left "(127) error finding bg color: /bin/sh: poop: command not found\n"
```

(One thing I'm not sure about is whether it's a good idea to handle `Text` or if to keep stuff `String` until the end. But that's pretty minor I guess.)

This `EitherT` monad is pretty neat! 💣 💵

**Comment by emhoracek** [comment]
@ear All this stuff is very interesting!

I'll go into more detail tomorrow, but I don't think there's any need to push `tryIO` down into the functions that run commands -- I'd prefer to limit what needs to be `EitherT`. Since those calls to `System.Process` are internal to the function, they can stay IO. But I get what you're saying about it not seeming consistent with how we're handling exceptions in other places!

**Comment by ear** [comment]
Yeah please don't take all of this as prescriptive: I'm just trying to understand myself. I'm curious to see what you think when you get a chance to play around with this style.

**Comment by emhoracek** [comment]
Let's use `mapLeft` instead of `first` -- pedagogical reasons are good reasons. :) Everything else looks great! Thanks so much!

**Comment by emhoracek** [comment]
Thanks again for the PR!

**Pull request merged**
